//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cferc_website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MartinezDBEntities : DbContext
    {
        public MartinezDBEntities()
            : base("name=MartinezDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<area> areas { get; set; }
        public DbSet<data_table> data_table { get; set; }
        public DbSet<industry> industries { get; set; }
        public DbSet<measure> measures { get; set; }
        public DbSet<series> series { get; set; }
        public DbSet<regional_db> regional_db { get; set; }
    
        public virtual int procPivotQuery(string yrBegin, string yrEnd, string measureName, string industryName)
        {
            var yrBeginParameter = yrBegin != null ?
                new ObjectParameter("yrBegin", yrBegin) :
                new ObjectParameter("yrBegin", typeof(string));
    
            var yrEndParameter = yrEnd != null ?
                new ObjectParameter("yrEnd", yrEnd) :
                new ObjectParameter("yrEnd", typeof(string));
    
            var measureNameParameter = measureName != null ?
                new ObjectParameter("measureName", measureName) :
                new ObjectParameter("measureName", typeof(string));
    
            var industryNameParameter = industryName != null ?
                new ObjectParameter("industryName", industryName) :
                new ObjectParameter("industryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procPivotQuery", yrBeginParameter, yrEndParameter, measureNameParameter, industryNameParameter);
        }
    }
}
