//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cferc_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regional_db
    {
        public string areaID { get; set; }
        public string areaName { get; set; }
        public string industryID { get; set; }
        public string industryName { get; set; }
        public string measureID { get; set; }
        public string measureName { get; set; }
        public string seriesID { get; set; }
        public string blsTable { get; set; }
        public string beginYear { get; set; }
        public string endYear { get; set; }
        public string beginPeriod { get; set; }
        public string endPeriod { get; set; }
        public string fipsCode { get; set; }
        public long valID { get; set; }
        public Nullable<int> year { get; set; }
        public string period { get; set; }
        public Nullable<long> value { get; set; }
    }
}
