//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cferc_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class series
    {
        public series()
        {
            this.data_table = new HashSet<data_table>();
        }
    
        public string seriesID { get; set; }
        public string areaID { get; set; }
        public string measureID { get; set; }
        public string industryID { get; set; }
        public string blsTable { get; set; }
        public string beginYear { get; set; }
        public string endYear { get; set; }
        public string beginPeriod { get; set; }
        public string endPeriod { get; set; }
        public string fipsCode { get; set; }
    
        public virtual area area { get; set; }
        public virtual ICollection<data_table> data_table { get; set; }
        public virtual industry industry { get; set; }
        public virtual measure measure { get; set; }
    }
}
